version: "3"

dotenv: [".env"]

tasks:
  run:
    desc: Run the HTTP server
    cmds:
      - go run ./cmd/task_manager_go
    silent: true

  test:
    desc: Run all tests
    cmds:
      - go test ./...
    silent: true

  build:
    desc: Build binary
    cmds:
      - go build -o bin/server ./cmd/task_manager_go
    silent: true

  migrate:new:
    desc: Create a new migration file ( Usage :- task migrate:new NAME=create_users_table)
    cmds:
      - migrate create -ext sql -dir internal/database/migrations -seq {{.NAME}}

  migrate:up:
    desc: Apply database migrations
    cmds:
      - migrate -database "{{.DATABASE_URL}}" -path internal/database/migrations up

  migrate:down:
    desc: Rollback last migration
    cmds:
      - migrate -database "{{.DATABASE_URL}}" -path internal/database/migrations down 1
